spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tally?autoReconnect=true&useUnicode=yes&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.orm.jpa: debug
    org.springframework.transaction.interceptor: trace
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
